OMV_GPIO_DEFINE(A, 4, AF13, DCMI)
OMV_GPIO_DEFINE(A, 5, NONE, GPIO)
OMV_GPIO_DEFINE(A, 6, AF13, DCMI)
OMV_GPIO_DEFINE(A, 8, AF1, TIM1)
OMV_GPIO_DEFINE(A, 10, NONE, GPIO)
OMV_GPIO_DEFINE(A, 15, AF6, SPI3)
OMV_GPIO_DEFINE(B, 3, AF6, SPI3)
OMV_GPIO_DEFINE(B, 4, NONE, GPIO)
// OMV_GPIO_DEFINE(B, 4,  AF6,  SPI3)  // 注释重复定义
OMV_GPIO_DEFINE(B, 5, AF7, SPI3)
OMV_GPIO_DEFINE(B, 6, AF13, DCMI)
OMV_GPIO_DEFINE(B, 7, AF13, DCMI)
OMV_GPIO_DEFINE(B, 8, AF4, I2C1)
OMV_GPIO_DEFINE(B, 9, AF4, I2C1)
OMV_GPIO_DEFINE(B, 10, NONE, GPIO)
OMV_GPIO_DEFINE(B, 10, AF4, I2C2)
OMV_GPIO_DEFINE(B, 11, NONE, GPIO)
OMV_GPIO_DEFINE(B, 11, AF4, I2C2)
OMV_GPIO_DEFINE(B, 12, NONE, GPIO)
OMV_GPIO_DEFINE(B, 12, AF5, SPI2)
OMV_GPIO_DEFINE(B, 13, AF5, SPI2)
OMV_GPIO_DEFINE(B, 14, AF5, SPI2)
OMV_GPIO_DEFINE(B, 15, AF5, SPI2)
OMV_GPIO_DEFINE(C, 6, AF13, DCMI)
OMV_GPIO_DEFINE(C, 7, AF13, DCMI)
OMV_GPIO_DEFINE(D, 7, NONE, GPIO)
OMV_GPIO_DEFINE(D, 12, NONE, GPIO)
// OMV_GPIO_DEFINE(D, 13, NONE, GPIO) // 注释重复定义，用于QSPI
OMV_GPIO_DEFINE(E, 4, AF13, DCMI)
OMV_GPIO_DEFINE(E, 5, AF13, DCMI)
OMV_GPIO_DEFINE(E, 6, AF13, DCMI)
OMV_GPIO_DEFINE(G, 10, AF13, DCMI)
OMV_GPIO_DEFINE(G, 11, AF13, DCMI)

/* ---------------------------------- 新增部分 ---------------------------------- */

OMV_GPIO_DEFINE(A, 5, AF5, SPI1)   // LCD SCL
OMV_GPIO_DEFINE(A, 6, AF5, SPI1)   // LCD MISO (备用)
OMV_GPIO_DEFINE(A, 7, AF5, SPI1)   // LCD SDA (MOSI)
OMV_GPIO_DEFINE(A, 15, AF5, SPI1)  // LCD CS
OMV_GPIO_DEFINE(D, 10, NONE, GPIO) // LCD BL
OMV_GPIO_DEFINE(D, 2, NONE, GPIO)  // LCD DC

OMV_GPIO_DEFINE(C, 0, NONE, GPIO) // STROBE
OMV_GPIO_DEFINE(D, 3, AF13, DCMI) // OV Y7
OMV_GPIO_DEFINE(E, 0, AF13, DCMI) // OV Y4
OMV_GPIO_DEFINE(E, 1, AF13, DCMI) // OV Y5
OMV_GPIO_DEFINE(E, 3, NONE, GPIO) // OV PWDBN

OMV_GPIO_DEFINE(C, 3, NONE, GPIO) // SPI3 CS
OMV_GPIO_DEFINE(C, 11, AF6, SPI3) // SPI3 MISO
OMV_GPIO_DEFINE(C, 12, AF6, SPI3) // SPI3 MOSI