OMV_GPIO_DEFINE(A, 4, AF13, DCMI) // OV HREF
OMV_GPIO_DEFINE(A, 5, AF5, SPI1)
OMV_GPIO_DEFINE(A, 6, AF13, DCMI) // OV PCLK
OMV_GPIO_DEFINE(A, 7, AF5, SPI1)
OMV_GPIO_DEFINE(A,15, AF5, SPI1) // LCD CS
OMV_GPIO_DEFINE(A, 8, AF1, TIM1)
OMV_GPIO_DEFINE(A, 10, NONE, GPIO)
OMV_GPIO_DEFINE(A, 15, NONE, GPIO)
OMV_GPIO_DEFINE(A, 11, AF10, OTG_FS)    // USB DM - 缺少
OMV_GPIO_DEFINE(A, 12, AF10, OTG_FS)    // USB DP - 缺少
OMV_GPIO_DEFINE(B, 2, AF9, QUADSPI) // QUADSPI CLK
OMV_GPIO_DEFINE(B, 3, AF6, SPI3)
OMV_GPIO_DEFINE(B, 4, NONE, GPIO)
OMV_GPIO_DEFINE(B, 4, AF6, SPI3)
OMV_GPIO_DEFINE(B, 5, AF7, SPI3)
OMV_GPIO_DEFINE(B, 6, AF10, QUADSPI) // QUADSPI CS#
OMV_GPIO_DEFINE(B, 6, AF13, DCMI)
OMV_GPIO_DEFINE(B, 7, AF13, DCMI) // OV VSYNC
OMV_GPIO_DEFINE(B, 8, AF4, I2C1)
OMV_GPIO_DEFINE(B, 9, AF4, I2C1)
OMV_GPIO_DEFINE(B, 10, NONE, GPIO)
OMV_GPIO_DEFINE(B, 10, AF4, I2C2) // OV SCL
OMV_GPIO_DEFINE(B, 11, NONE, GPIO)
OMV_GPIO_DEFINE(B, 11, AF4, I2C2) // OV SDA
OMV_GPIO_DEFINE(B, 12, NONE, GPIO)
OMV_GPIO_DEFINE(B, 12, AF5, SPI2)
OMV_GPIO_DEFINE(B, 13, AF5, SPI2)
OMV_GPIO_DEFINE(B, 14, AF5, SPI2)
OMV_GPIO_DEFINE(B, 15, AF5, SPI2)
OMV_GPIO_DEFINE(C, 0, NONE, GPIO) // STROBE
OMV_GPIO_DEFINE(C, 3, NONE, GPIO)
OMV_GPIO_DEFINE(C, 6, AF13, DCMI) // OV Y
OMV_GPIO_DEFINE(C, 7, AF13, DCMI) // OV Y3
OMV_GPIO_DEFINE(C, 9, AF9, QUADSPI)  // QUADSPI DI (IO0)
OMV_GPIO_DEFINE(C, 10, AF9, QUADSPI) // QUADSPI DO (IO1)
OMV_GPIO_DEFINE(C, 11, AF6, SPI3)
OMV_GPIO_DEFINE(C, 12, AF6, SPI3)
OMV_GPIO_DEFINE(D, 2, NONE, GPIO)
OMV_GPIO_DEFINE(C, 13, NONE, GPIO)      // LED - 缺少
OMV_GPIO_DEFINE(D, 3, AF13, DCMI) // OV Y7
OMV_GPIO_DEFINE(D, 7, NONE, GPIO)
OMV_GPIO_DEFINE(D, 10, NONE, GPIO)      // LCD BL - 缺少
OMV_GPIO_DEFINE(D, 13, AF9, QUADSPI) // QUADSPI HOLD#/RESET# (IO3)
OMV_GPIO_DEFINE(E, 0, AF13, DCMI) // OV Y4
OMV_GPIO_DEFINE(E, 1, AF13, DCMI) // OV Y5
OMV_GPIO_DEFINE(E, 2, AF9, QUADSPI)  // QUADSPI WP# (IO2)
OMV_GPIO_DEFINE(E, 3, NONE, GPIO) // OV PWDBN
OMV_GPIO_DEFINE(E, 4, AF13, DCMI) // OV Y6
OMV_GPIO_DEFINE(E, 5, AF13, DCMI) // OV Y8
OMV_GPIO_DEFINE(E, 6, AF13, DCMI) // OV Y9
OMV_GPIO_DEFINE(G, 10, AF13, DCMI)
OMV_GPIO_DEFINE(G, 11, AF13, DCMI)
// OMV_GPIO_DEFINE(NRST, 0, NONE, GPIO)    // OV RST (NRST 特殊处理，具体实现依赖于平台)